name: Spellcheck Action
on: workflow_dispatch

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    # The checkout step
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@0.47.0
      name: Spellcheck
      with:
        source_files: README.md
        task_name: Markdown
        output_file: spellcheck-output.txt
    - uses: actions/upload-artifact@v4
      if: '!cancelled()' # Do not upload artifact if job was cancelled
      with:
        name: Spellcheck Output
        path: spellcheck-output.txt
    # Create GitHub Issue step
    - name: Create GitHub Issue
      if: always()
      uses: JasonEtco/create-an-issue@v2
      with:
        title: "Spellcheck Report"
        body: |
          The following issues were found during the spellcheck:
          ```
          ${{ steps.build.outputs.spellcheck-output }}
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
